version: "3"
services:
  ps-db-user:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - user_volumes:/var/lib/postgresql
  ps-db-data:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - data_volumes:/var/lib/postgresql
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    volumes:
      - .minio:/data
    command: server --console-address ":9101" /data
    # 9000 is used by System on Windows
    ports:
      - 9100:9000
      - 9101:9001
volumes:
  user_volumes:
  data_volumes:
